'use client';
import { useEffect, useState } from 'react';
import { ArrowDown, ArrowRight, BatteryCharging, Check, ChevronDown, Download, Gift, Headphones, MapPin, Menu, MessageCircle, Music2, PackageCheck, Play, ShieldCheck, Smartphone, Sparkles, Watch, Wifi, X } from 'lucide-react';

const whatsapp='https://wa.me/593962981931?text=Hola%2C%20quiero%20informaci%C3%B3n%20sobre%20el%20smartwatch';
const features=[
  {icon:Smartphone,n:'01',title:'Un mini celular en tu muñeca',text:'Lleva tus aplicaciones y redes sociales contigo, sin perder el ritmo.'},
  {icon:Music2,n:'02',title:'Tu música, siempre cerca',text:'Reproduce tus canciones y aprovecha su memoria interna donde vayas.'},
  {icon:Download,n:'03',title:'Descarga aplicaciones',text:'Personaliza tu experiencia con las apps que necesitas cada día.'},
  {icon:Watch,n:'04',title:'Pantalla táctil Full HD',text:'Una experiencia visual nítida, fluida e intuitiva en cada toque.'}
];
const faqs=[
  ['¿Realizan envíos fuera de Guayaquil?','Sí. El envío es totalmente gratis a nivel nacional. Escríbenos por WhatsApp para coordinar tu pedido.'],
  ['¿Qué incluye mi compra?','Tu smartwatch incluye mica de hidrogel, cargador magnético y correas. Todo listo para que empieces a usarlo.'],
  ['¿Cómo puedo comprarlo?','Toca cualquiera de los botones de WhatsApp. Te atenderemos directamente para confirmar disponibilidad y datos de envío.']
];
export default function Home(){
 const [menuOpen,setMenuOpen]=useState(false); const [openFaq,setOpenFaq]=useState(0);
 useEffect(()=>{const o=new IntersectionObserver(es=>es.forEach(e=>e.isIntersecting&&e.target.classList.add('revealed')),{threshold:.14});document.querySelectorAll('.reveal').forEach(el=>o.observe(el));return()=>o.disconnect()},[]);
 return <main>
  <nav className="nav"><a className="brand" href="#inicio"><span className="brand-mark"><Watch size={19}/></span><span>NOVA<span>WATCH</span></span></a><div className={`nav-links ${menuOpen?'open':''}`}><a href="#beneficios" onClick={()=>setMenuOpen(false)}>Beneficios</a><a href="#incluye" onClick={()=>setMenuOpen(false)}>Qué incluye</a><a href="#preguntas" onClick={()=>setMenuOpen(false)}>Preguntas</a><a className="nav-cta" href={whatsapp} target="_blank" rel="noreferrer"><MessageCircle size={17}/> Comprar ahora</a></div><button className="menu" onClick={()=>setMenuOpen(!menuOpen)} aria-label="Abrir menú">{menuOpen?<X/>:<Menu/>}</button></nav>
  <section id="inicio" className="hero"><div className="hero-glow"/><div className="hero-copy"><div className="eyebrow"><span/> Tecnología que se mueve contigo</div><h1>Todo tu mundo.<br/><em>En tu muñeca.</em></h1><p>Redes sociales, música, aplicaciones y mucho más. La potencia de un mini celular en un smartwatch diseñado para seguirte el ritmo.</p><div className="hero-actions"><a className="button primary" href={whatsapp} target="_blank" rel="noreferrer">Quiero el mío <ArrowRight size={18}/></a><a className="button secondary" href="#beneficios"><Play size={16} fill="currentColor"/> Descubrir más</a></div><div className="trust-row"><span><PackageCheck size={18}/> Envío gratis nacional</span><span><MapPin size={18}/> Desde Guayaquil</span></div></div><div className="hero-visual"><div className="orbit orbit-one"/><div className="orbit orbit-two"/><img src="/smartwatch-hero.png" alt="Smartwatch negro con pantalla táctil y aplicaciones"/><div className="floating-chip chip-one"><Wifi size={18}/><span><b>Siempre conectado</b>Redes y aplicaciones</span></div><div className="floating-chip chip-two"><Headphones size={18}/><span><b>Música contigo</b>Memoria interna</span></div></div><a href="#beneficios" className="scroll-cue" aria-label="Ver beneficios"><ArrowDown size={18}/></a></section>
  <section className="marquee"><div className="marquee-track">{[...Array(2)].flatMap((_,i)=>['Pantalla Full HD','Aplicaciones','Redes sociales','Música','Memoria interna'].map(x=><span key={`${i}-${x}`}>{x}<i>✦</i></span>))}</div></section>
  <section id="beneficios" className="section features-section"><div className="section-head reveal"><div><span className="kicker">Más que un reloj</span><h2>Hecho para acompañar<br/>cada parte de tu día.</h2></div><p>Conectividad, entretenimiento y estilo en un dispositivo compacto y potente.</p></div><div className="feature-grid">{features.map(({icon:Icon,n,title,text})=><article className="feature-card reveal" key={n}><div className="feature-top"><span className="feature-icon"><Icon/></span><span className="feature-number">{n}</span></div><h3>{title}</h3><p>{text}</p><div className="feature-line"/></article>)}</div></section>
  <section className="experience section"><div className="experience-card reveal"><div className="experience-copy"><span className="kicker light">Una pantalla que responde</span><h2>Todo fluye<br/>con un toque.</h2><p>Navega por tus apps, controla tu música y mantente conectado desde una pantalla táctil Full HD brillante y fácil de usar.</p><div className="stats"><div><strong>Full HD</strong><span>Pantalla nítida</span></div><div><strong>100%</strong><span>Táctil e intuitiva</span></div></div></div><div className="screen-demo"><div className="screen-ring"/><div className="watch-screen"><div className="screen-time">10:09</div><div className="app-grid">{[Music2,MessageCircle,Wifi,Play,Smartphone,Sparkles].map((Icon,i)=><span key={i}><Icon size={20}/></span>)}</div></div></div></div></section>
  <section id="incluye" className="section bundle"><div className="bundle-intro reveal"><span className="kicker">Tu compra incluye</span><h2>Más completo.<br/><em>Sin pagar de más.</em></h2><p>Te entregamos todo lo necesario para protegerlo, cargarlo y llevarlo a tu estilo desde el primer día.</p></div><div className="bundle-list">{[['Mica de hidrogel','Protección para tu pantalla','Gratis',ShieldCheck],['Cargador magnético','Carga fácil y sin complicaciones','Incluido',BatteryCharging],['Correas','Cambia tu estilo cuando quieras','Incluidas',Watch],['Envío nacional','Recíbelo donde estés','Gratis',PackageCheck]].map(([title,text,badge,Icon],i)=>{const I=Icon as typeof Watch;return <div className="bundle-item reveal" key={title as string}><span className="bundle-index">0{i+1}</span><span className="bundle-icon"><I/></span><div><h3>{title as string}</h3><p>{text as string}</p></div><b>{badge as string}</b></div>})}</div></section>
  <section className="offer section"><div className="offer-card reveal"><div className="gift"><Gift/></div><span className="kicker light">Oferta completa</span><h2>Tu próximo smartwatch<br/>está a un mensaje.</h2><p>Escríbenos para consultar precio, colores y disponibilidad. Enviamos gratis a todo Ecuador.</p><a className="button white" href={whatsapp} target="_blank" rel="noreferrer"><MessageCircle size={19}/> Comprar por WhatsApp</a><div className="offer-note"><Check size={16}/> Atención directa desde Guayaquil</div></div></section>
  <section id="preguntas" className="section faq"><div className="faq-title reveal"><span className="kicker">Antes de comprar</span><h2>Preguntas<br/>frecuentes.</h2></div><div className="faq-list reveal">{faqs.map(([q,a],i)=><div className={`faq-item ${openFaq===i?'active':''}`} key={q}><button onClick={()=>setOpenFaq(openFaq===i?-1:i)}><span>{q}</span><ChevronDown/></button><div className="faq-answer"><p>{a}</p></div></div>)}</div></section>
  <footer><div className="footer-brand"><a className="brand" href="#inicio"><span className="brand-mark"><Watch size={19}/></span><span>NOVA<span>WATCH</span></span></a><p>Tecnología para llevar.</p></div><div className="footer-contact"><span>Guayaquil, Ecuador</span><a href={whatsapp} target="_blank" rel="noreferrer">+593 96 298 1931 <ArrowRight size={16}/></a></div><p className="copyright">© 2026 NovaWatch. Todos los derechos reservados.</p></footer><a className="whatsapp-float" href={whatsapp} target="_blank" rel="noreferrer" aria-label="Contactar por WhatsApp"><MessageCircle fill="currentColor"/></a>
 </main>
}
